import { type Question } from "@/types";

export const questionsData: Question[] = [
    {
        id: 0,
        slug: "two-sum",
        company: "Google",
        title: "Two Sum",
        topic: "Arrays",
        difficulty: "Easy",
        likes: "99%",
        views: "3.5M",
        duration: "Easy",
        img: "bg-blue-500",
        desc: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
    },
    {
        id: 1,
        slug: "design-global-file-storage",
        company: "Google",
        title: "Design a Global File Storage System",
        topic: "System Design",
        difficulty: "Hard",
        likes: "98%",
        views: "1.2M",
        duration: "Hard",
        img: "bg-blue-600",
        desc: "Design a distributed file storage system like Google Drive. Requirements: Upload, download, delete, sync, conflict resolution.",
    },
    {
        id: 2,
        slug: "merge-k-sorted-lists",
        company: "Google",
        title: "Merge k Sorted Lists",
        topic: "Heaps",
        difficulty: "Hard",
        likes: "95%",
        views: "850K",
        duration: "Hard",
        img: "bg-blue-600",
        desc: "Merge k sorted linked lists and return it as one sorted list.",
    },
    {
        id: 3,
        slug: "find-missing-number",
        company: "Amazon",
        title: "Find the Missing Number",
        topic: "Arrays",
        difficulty: "Easy",
        likes: "99%",
        views: "2.1M",
        duration: "Easy",
        img: "bg-yellow-600",
        desc: "Given an array nums containing n distinct numbers in the range [0, n], return the only number in the range that is missing.",
    },
    {
        id: 4,
        slug: "reverse-linked-list-group-k",
        company: "Microsoft",
        title: "Reverse Linked List Group K",
        topic: "LinkedList",
        difficulty: "Medium",
        likes: "92%",
        views: "600K",
        duration: "Med",
        img: "bg-sky-600",
        desc: "Reverse the nodes of the list k at a time.",
    },
    {
        id: 5,
        slug: "ride-matching-algorithm",
        company: "Uber",
        title: "Ride Matching Algorithm",
        topic: "System Design",
        difficulty: "Medium",
        likes: "97%",
        views: "1.5M",
        duration: "Med",
        img: "bg-neutral-800",
        desc: "Design the core matching engine for a ride-sharing app.",
    },
    {
        id: 6,
        slug: "group-anagrams",
        company: "Netflix",
        title: "Group Anagrams",
        topic: "Strings",
        difficulty: "Medium",
        likes: "94%",
        views: "920K",
        duration: "Med",
        img: "bg-red-600",
        desc: "Given an array of strings, group the anagrams together.",
    },
    {
        id: 7,
        slug: "binary-tree-vertical-order",
        company: "Meta",
        title: "Binary Tree Vertical Order",
        topic: "Trees",
        difficulty: "Hard",
        likes: "91%",
        views: "430K",
        duration: "Hard",
        img: "bg-blue-800",
        desc: "Return the vertical order traversal of a binary tree.",
    },
    {
        id: 8,
        slug: "longest-substring-no-repeats",
        company: "Apple",
        title: "Longest Substring No Repeats",
        topic: "Strings",
        difficulty: "Medium",
        likes: "96%",
        views: "1.8M",
        duration: "Med",
        img: "bg-neutral-700",
        desc: "Find the length of the longest substring without repeating characters.",
    },
];
